enum FilesScenario: String, Equatable, CaseIterable {
    case browser = "files.browser"
    case browserTruncated = "files.browser.truncated"
    case browserUnreachable = "files.browser.unreachable"
    case preview = "files.preview"
    case previewImage = "files.preview.image"
    case previewVector = "files.preview.vector"
    case viewer = "files.viewer"
    case source = "files.source"
    case sourceRefusal = "files.source.refusal"
    case json = "files.json"
    case jsonTree = "files.json.tree"
    case jsonTreeExpanded = "files.json.tree.expanded"
    case markdown = "files.markdown"
    case image = "files.image"
    case imageComparison = "files.image.comparison"
    case svg = "files.svg"
    case video = "files.video"
    case videoUnsupported = "files.video.unsupported"
}
