nonisolated enum FileIconTables: Sendable {
    static let fileNames: [String: String] = merge([
        FileIconFileNameTable0.table,
        FileIconFileNameTable1.table,
        FileIconFileNameTable2.table,
    ])

    static let fileExtensions: [String: String] = merge([
        FileIconExtensionTable0.table,
        FileIconExtensionTable1.table,
        FileIconExtensionTable2.table,
        FileIconExtensionTable3.table,
    ])

    static let folderNames: [String: String] = merge([
        FileIconFolderTable0.table,
        FileIconFolderTable1.table,
        FileIconFolderTable2.table,
        FileIconFolderTable3.table,
    ])

    static let shippedIconNames: Set<String> = [
        "file",
        "swift",
        "objective-c",
        "objective-cpp",
        "c",
        "cpp",
        "h",
        "hpp",
        "typescript",
        "typescript-def",
        "javascript",
        "react",
        "react_ts",
        "json",
        "yaml",
        "toml",
        "markdown",
        "mdx",
        "html",
        "css",
        "sass",
        "less",
        "console",
        "python",
        "python-misc",
        "go",
        "go-mod",
        "rust",
        "ruby",
        "gemfile",
        "docker",
        "git",
        "lock",
        "image",
        "svg",
        "video",
        "audio",
        "zip",
        "font",
        "pdf",
        "xml",
        "database",
        "graphql",
        "proto",
        "java",
        "kotlin",
        "csharp",
        "php",
        "lua",
        "dart",
        "vue",
        "svelte",
        "editorconfig",
        "npm",
        "yarn",
        "pnpm",
        "eslint",
        "prettier",
        "tsconfig",
        "jsconfig",
        "makefile",
        "cmake",
        "just",
        "key",
        "certificate",
        "readme",
        "license",
        "changelog",
        "settings",
        "document",
        "exe",
        "lib",
        "nodejs",
        "folder",
        "folder-open",
        "folder-root",
        "folder-root-open",
        "folder-src",
        "folder-src-open",
        "folder-dist",
        "folder-dist-open",
        "folder-git",
        "folder-git-open",
        "folder-github",
        "folder-github-open",
        "folder-images",
        "folder-images-open",
        "folder-docs",
        "folder-docs-open",
        "folder-test",
        "folder-test-open",
        "folder-config",
        "folder-config-open",
        "folder-scripts",
        "folder-scripts-open",
        "folder-node",
        "folder-node-open",
        "folder-rust",
        "folder-rust-open",
    ]

    private static func merge(_ parts: [[String: String]]) -> [String: String] {
        var result: [String: String] = [:]
        result.reserveCapacity(parts.reduce(0) { $0 + $1.count })
        for part in parts {
            for (key, value) in part {
                result[key] = value
            }
        }
        return result
    }
}
